/* 127.0.0.1 에 MariaDB (TCP/IP) 을(를) 통해 연결 중, 사용자 이름 "root", 암호 사용: Yes… */
SELECT CONNECTION_ID();
/* 연결됨. 스레드-ID: 4 */
/* 문자 집합: utf8mb4 */
SHOW STATUS;
SELECT NOW();
SHOW VARIABLES;
SHOW DATABASES;
/* "root" 세션 시작 */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='mysql';
SHOW TABLE STATUS FROM `mysql`;
SHOW FUNCTION STATUS WHERE `Db`='mysql';
SHOW PROCEDURE STATUS WHERE `Db`='mysql';
SHOW TRIGGERS FROM `mysql`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='information_schema';
SHOW TABLE STATUS FROM `information_schema`;
SHOW FUNCTION STATUS WHERE `Db`='information_schema';
SHOW PROCEDURE STATUS WHERE `Db`='information_schema';
SHOW TRIGGERS FROM `information_schema`;
SHOW EVENTS FROM `information_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='mysql';
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='test';
SHOW TABLE STATUS FROM `test`;
SHOW FUNCTION STATUS WHERE `Db`='test';
SHOW PROCEDURE STATUS WHERE `Db`='test';
SHOW TRIGGERS FROM `test`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='test';
USE `test`;
USE `performance_schema`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='performance_schema';
SHOW TABLE STATUS FROM `performance_schema`;
SHOW FUNCTION STATUS WHERE `Db`='performance_schema';
SHOW PROCEDURE STATUS WHERE `Db`='performance_schema';
SHOW TRIGGERS FROM `performance_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='performance_schema';
USE `test`;
DROP DATABASE `test`;
SHOW DATABASES;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='information_schema';
SHOW TABLE STATUS FROM `information_schema`;
SHOW FUNCTION STATUS WHERE `Db`='information_schema';
SHOW PROCEDURE STATUS WHERE `Db`='information_schema';
SHOW TRIGGERS FROM `information_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='information_schema';
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='mysql';
SHOW TABLE STATUS FROM `mysql`;
SHOW FUNCTION STATUS WHERE `Db`='mysql';
SHOW PROCEDURE STATUS WHERE `Db`='mysql';
SHOW TRIGGERS FROM `mysql`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='mysql';
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='performance_schema';
SHOW TABLE STATUS FROM `performance_schema`;
SHOW FUNCTION STATUS WHERE `Db`='performance_schema';
SHOW PROCEDURE STATUS WHERE `Db`='performance_schema';
SHOW TRIGGERS FROM `performance_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='performance_schema';
SHOW COLLATION;
CREATE DATABASE `create database bigdb` /*!40100 COLLATE 'utf8_general_ci' */;
SHOW DATABASES;
/* "root" 세션 시작 */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='create database bigdb';
SHOW TABLE STATUS FROM `create database bigdb`;
SHOW FUNCTION STATUS WHERE `Db`='create database bigdb';
SHOW PROCEDURE STATUS WHERE `Db`='create database bigdb';
SHOW TRIGGERS FROM `create database bigdb`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='create database bigdb';
USE `create database bigdb`;
DROP DATABASE `create database bigdb`;
SHOW DATABASES;
CREATE DATABASE `bigdb` /*!40100 COLLATE 'utf8_general_ci' */;
SHOW DATABASES;
/* "root" 세션 시작 */
USE `bigdb`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='bigdb';
SHOW TABLE STATUS FROM `bigdb`;
SHOW FUNCTION STATUS WHERE `Db`='bigdb';
SHOW PROCEDURE STATUS WHERE `Db`='bigdb';
SHOW TRIGGERS FROM `bigdb`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='bigdb';
FLUSH PRIVILEGES;
SHOW COLUMNS FROM `mysql`.`user`;
SELECT `user`, `host`, IF(LENGTH(password)>0, password, authentication_string) AS `password` FROM `mysql`.`user`;
CREATE USER 'java'@'localhost' IDENTIFIED BY 'java';
GRANT ALTER, SHOW VIEW, SHOW DATABASES, SELECT, PROCESS, EXECUTE, CREATE ROUTINE, CREATE, ALTER ROUTINE, CREATE VIEW, CREATE TEMPORARY TABLES, CREATE TABLESPACE, EVENT, DROP, DELETE, REFERENCES, INSERT, INDEX, CREATE USER, UPDATE, TRIGGER, LOCK TABLES, FILE, REPLICATION SLAVE, REPLICATION CLIENT, RELOAD, SUPER, SHUTDOWN  ON *.* TO 'java'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'java'@'localhost';
SHOW GRANTS FOR 'mariadb.sys'@'localhost';
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='mysql';
SHOW TABLE STATUS FROM `mysql`;
SHOW FUNCTION STATUS WHERE `Db`='mysql';
SHOW PROCEDURE STATUS WHERE `Db`='mysql';
SHOW TRIGGERS FROM `mysql`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='mysql';
SHOW GRANTS FOR 'root'@'mingki';
SHOW GRANTS FOR 'root'@'127.0.0.1';
SHOW GRANTS FOR 'root'@'%';
SHOW GRANTS FOR 'root'@'::1';
SHOW GRANTS FOR 'root'@'%';
SHOW GRANTS FOR 'mariadb.sys'@'localhost';
SHOW GRANTS FOR 'root'@'localhost';
SHOW GRANTS FOR 'root'@'mingki';
SHOW GRANTS FOR 'root'@'127.0.0.1';
SHOW GRANTS FOR 'root'@'::1';
SHOW GRANTS FOR 'root'@'%';
SHOW GRANTS FOR 'mariadb.sys'@'localhost';
SHOW GRANTS FOR 'root'@'localhost';
SHOW GRANTS FOR 'root'@'127.0.0.1';
SHOW GRANTS FOR 'root'@'::1';
SHOW GRANTS FOR 'root'@'%';
SHOW GRANTS FOR 'java'@'localhost';
CREATE USER 'java'@'%' IDENTIFIED BY 'java';
GRANT ALTER, SHOW VIEW, SHOW DATABASES, SELECT, PROCESS, EXECUTE, CREATE ROUTINE, CREATE, ALTER ROUTINE, CREATE VIEW, CREATE TEMPORARY TABLES, CREATE TABLESPACE  ON *.* TO 'java'@'%';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'java'@'%';
SET PASSWORD FOR 'java'@'%' = PASSWORD('tiger');
RENAME USER 'java'@'%' TO 'scott'@'%';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'scott'@'%';